### ISSUE TITLE
Suggestion: Option to keep bot in empty channel

### ISSUE THREAD

**Issue by TehSeph** [appellation/monstercat#14]
A per-server config to keep the bot in an empty voice channel to avoid `mc! join` spam or keep bot limited to a single channel would be nice. I understand this is probably done to cut down on bandwidth but would just stopping playback when the channel is empty not work the same? (sorry if this is a dumb question 😆)

**Comment by appellation** [comment]
I've been thinking about something along these lines.  I'm reticent to add guild config, but I will test with just leaving the bot in voice channels until requested.
