### ISSUE TITLE
Suggestion: Swap artist and title in game name

### ISSUE THREAD

**Issue by TehSeph** [appellation/monstercat#15]
Just a pet-peeve really, but could you swap the parsed strings here
https://github.com/appellation/monstercat/blob/master/src/handlers/init.js#L25
```
parsed = `${parsed[1]} - ${parsed[2].replace(/ - (Listen now: \S+ Tweet it: \S+|Listen on Spotify: \S+)$/, '')}`;
```
to fit the standard format of `artist - title` (ie: [Tokyo Machine - BLAST](https://www.youtube.com/watch?v=ycgtC0EDOfk))

**Comment by appellation** [comment]
PR and I can merge.
