### ISSUE TITLE
Not issue, more recommendation/question

### ISSUE THREAD

**Issue by Scalper** [appellation/monstercat#19]
Is there a way to pull the information for the bot so that I can display on stream the now playing without too much work? Or is there a possibility for getting the bot hooked into twitch as well for a now-playing feature? Or maybe a way Nightbot can query to a hook/site/something to get the current song?

**Comment by appellation** [comment]
Monstercat has a Twitch bot that you can add to your stream which will accomplish what you are looking for.  https://www.twitch.tv/monstercat
