### ISSUE TITLE
Not reading commands

### ISSUE THREAD

**Issue by ExplodingXMango** [appellation/monstercat#3]
The bot will not acknowledge or react to commands. User is in a voice chat and uses prefix @Monstercat while prompting [Join] and does not receive a response or action, the bot is not blocked from access to said channel.

**Comment by appellation** [comment]
Thanks for noting this. I was concerned about an issue like this but I'm currently unable to reproduce. I'll work on testing to find it and get back to you. In the meantime I'll try to restart and hopefully fix the problem temporarily.

**Comment by appellation** [comment]
@ExplodingXMango I am unable to reproduce this problem.  Do you have any details surrounding the circumstances of your issue?
