### ISSUE TITLE
2 things

### ISSUE THREAD

**Issue by G4meCore** [appellation/monstercat#5]
First: i tried mostely everything examples:( @Monstercat join; @Monstercat !Join ) and many more, but the bot didnt reacted. Can you simply explain, what i have to type in?
Second: is there a way the bot autotells the current running song or saying it by a command? and if not, did you thought about adding it?

sry for bad englisch i am German and thanks for the help (if you help me :> )

**Comment by appellation** [comment]
Thank you for letting me know. I believe this is the same issue as #3. Can you tell me whether this problem occurred after the bot had already been playing?

**Comment by G4meCore** [comment]
the bot joined my server and then did nothing

**Comment by G4meCore** [comment]
he never startet

**Comment by appellation** [comment]
Can you confirm that the bot has permissions to join the voice channel you were in?

**Comment by appellation** [comment]
Regarding the comment about displaying the current song, that feature is definitely planned.

**Comment by G4meCore** [comment]
the bot got all permissions, first by his created Monstercat role + a role i created with all permissions, after it first didnt worked

**Comment by appellation** [comment]
I tested this in a brand new server and didn't have a problem.  I will wait about a day, though, in case it's an issue with the bot being online for a while (I tested this shortly after restarting).
