### ISSUE TITLE
Idk how to use the commands

### ISSUE THREAD

**Issue by Sunsetgalaxy** [appellation/monstercat#6]
I have the Bot on my server but I don't understand your commands or how the bot works. It literally makes no sense at all. If you could help me that would be highly appreciated.

**Comment by appellation** [comment]
Prefix commands with a mention: for instance `@Pleb help`.

**Comment by appellation** [comment]
Please note that the bot may be unresponsive at times.  I don't know why, and I'm waiting for improved libraries to come out.  In the meantime, try `@Monstercat leave` and then having it join again.
